version: '2'
services:
  toran:
    image: cedvan/toran-proxy:latest
    volumes:
          - ./storage/:/data/toran-proxy
          - ./ssh/:/data/toran-proxy/ssh
    ports:
      - 8080:80
      - 4443:443
    environment:
      - TORAN_HTTPS=false